[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lobbyist = "3JceRWanoEVZSqsY9UGtxPA4XsSAnSKDTNWp2Sp3QQLu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
upgradeable = false

[[test.genesis]]
address = "AMMyu265tkBpRW21iGQxKGLaves3gKm2JcMUqfXNSpqD"
program = "./tests/fixtures/amm.so"

[[test.genesis]]
address = "2NuwUH2Ld3x452kau9xwhyj8ofwsU6uCr7Ybyq8Ue6bt"
program = "./tests/fixtures/amm_exec.so"

[[test.genesis]]
address = "autowMzCbM29YXMgVG3T62Hkgo7RcyrvgQQkd54fDQL"
program = "./tests/fixtures/autocrat.so"

[[test.genesis]]
address = "GrazkQjktchTgSp9VTrLWn3dDht6Lmra9tAqQ7ebbjQ3"
program = "./tests/fixtures/autocrat_exec.so"

[[test.genesis]]
address = "VLTX1ishMBbcX3rdBWGssxawAo1Q2X2qxYFYqiGodVg"
program = "./tests/fixtures/conditional_vault.so"

[[test.genesis]]
address = "GieLGMFVoCwSN4Mz1Tx3AFFf2kZfUKjyVrxZ7kKh6b9s"
program = "./tests/fixtures/conditional_vault_exec.so"
